command:
  - "streamlit"
  - "run"
  - "src/ui/streamlit_app.py"
  - "--server.port=8000"
  - "--server.headless=true"
  - "--server.address=0.0.0.0"

env:
  - name: "LLM_MODEL"
    value: "databricks/databricks-meta-llama-3-1-70b-instruct"
  - name: "DATA_PATH"
    value: "data/virtual_financial_advisor_data.csv"